import type { Metadata } from 'next'
import { AntdRegistry } from '@ant-design/nextjs-registry'

// Components
import RootLayoutClient from '@/components/layout/RootLayoutClient'

// Styles
import '@/styles/globals.css'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

interface Props {
  children: React.ReactNode
  collapsed: boolean
}

export default function RootLayout({ children }: Readonly<Props>) {
  return (
    <html lang="en">
      <body>
        <AntdRegistry>
          <RootLayoutClient>
            {children}
          </RootLayoutClient>
        </AntdRegistry>
      </body>
    </html>
  )
}
