import type { Metadata } from 'next'
import { AntdRegistry } from '@ant-design/nextjs-registry'

// Components
import RootLayoutClient from '@/components/layout/RootLayoutClient'

// Styles
import '@/styles/globals.css'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <RootLayoutClient>
          {children}
        </RootLayoutClient>
      </body>
    </html>
  )
}
